version: "3.1"
services:
  phabricator:
      build: ./app
      depends_on:
        - database
        - nginx
      links:
        - database
      ports:
        - 8081:80

  nginx:
    build: ./nginx-php-fpm
    ports:
      - 80
      - 443

  database:
      image: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=changeit
        - MYSQL_USER=mallory
        - MYSQL_PASSWORD=changeit
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      ports:
        - 3306

